# Generated by Django 5.0.1 on 2024-01-20 17:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("borrowing", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="borrowing",
            options={"ordering": ["-borrowing_date"]},
        ),
    ]
