# Generated by Django 5.0.1 on 2024-01-07 12:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("book", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="cover",
            field=models.CharField(
                choices=[("HC", "Hard"), ("SC", "Soft")], default="SC", max_length=2
            ),
        ),
    ]
