# Generated by Django 5.0.1 on 2024-01-20 15:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("book", "0002_alter_book_cover"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="book",
            options={"ordering": ["title"]},
        ),
    ]
